[project]
title = "Global Superstore Merchandising Overview"
version = "0.1.0"
port = 8501
slug = "global-superstore-merchandising"
entrypoint = "app.py"

[branding]
name = "Global Superstore Merchandising Overview"
logo = "images/logo.png"
favicon = "images/favicon.ico"
primaryColor = "#F89613"

[data.sample_json]
type = "json"
path = "data/sample_json.json"

[logging]
level = "INFO"
format = "%(asctime)s - %(name)s - %(levelname)s - %(message)s"